[NO-REF] chore(META): rewind to the 3.5.0 divergence point
* Reset the tree to 0a0d7b4e84, the merge-base of 3.4.0-HF3 and 3.5.0, so
  the 3.5.0 history can be replayed on top of the published OSS tip with no
  conflicts. Uses read-tree, which sets index and worktree only, leaving
  HEAD on the OSS tip so that commit stays the parent.

* Touches 748 files: 735 reverted to their divergence-point content and 13
  deleted; nothing is added. All of it is restored by the 243 commits
  replayed on top, so the resulting tree matches 3.5.0 exactly.

* Mechanical, with no reviewable intent of its own. It exists so the OSS
  branch keeps the published 3.4.0-OSS-HF3 commit as an ancestor instead of
  starting a disjoint history.

Change-Id: Ie0318de91090ea8c5bffc13dbaffcce458e7c80c
Signed-off-by: Yaniv <yaniv@nvidia.com>

diff --git a/RPM/buildrpm b/RPM/buildrpm
--- a/RPM/buildrpm
+++ b/RPM/buildrpm
@@ -1,8 +1,5 @@
 #!/bin/bash -x
 
-# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
-# SPDX-License-Identifier: Apache-2.0
-
 source ../transfer_lists
 
 print_help() {
@@ -29,11 +26,11 @@ usage:
 
 -n      --nhc               build nhc rpm
 
+--build-docker-image        build Docker image
+
 --dist-tag		    distribution tag to include in the RPM name
 
 --ubuntu		    create deb package for ubuntu
-
---fast-dev-build   skip os post install scripts (byte compile/compress) and strip only on node_modules (only for dev purposes)
 EOF
 }
 
@@ -83,8 +80,6 @@ buildRPMSetupTree() {
     fi
 }
 
-fastDevBuild=false
-
 pkgDeb() {
     if $isUbuntu || [[ "$DISTRIBUTION_INFO" =~ "Ubuntu" ]]; then
         echo "Building Ubuntu deb package..."
@@ -98,10 +93,7 @@ pkgDeb() {
             ATARGET=
         fi
 
-        start_alien=$(date +%s)
         alien --generate -k --scripts ~/"rpmbuild/RPMS/$ARCH/$packagePrefix"* $ATARGET
-        end_alien=$(date +%s)
-        echo "Alien generation took $((end_alien - start_alien)) seconds."
 
         packDir=$packagePrefix-$rpm_version
 
@@ -111,21 +103,11 @@ pkgDeb() {
                 sed -i -E "s/^[ ]*Depends:\s.*$/&, $requiresUbuntu/g" $packDir/debian/control
             fi
 
-            if [[ $fastDevBuild == true ]] && [[ $rpm == $mgmt ]]; then
-                echo "Excluding node_modules from dh_strip_nondeterminism..."
-                printf "\noverride_dh_strip_nondeterminism:\n\tdh_strip_nondeterminism -Xnode_modules\n" >> $packDir/debian/rules
-            fi
-
             echo "Setting gzip compression..."
             sed -i -E "s/dh_builddeb$/dh_builddeb -- -Zgzip/g" $packDir/debian/rules
 
             cd $packDir
-
-            start_dpkg=$(date +%s)
             dpkg-buildpackage -uc -us
-            end_dpkg=$(date +%s)
-            echo "dpkg-buildpackage took $((end_dpkg - start_dpkg)) seconds."
-
             cd ..
             rm -rf $packDir
             cp *.deb ../
@@ -187,6 +169,9 @@ case $key in
     nhcRPM=true
     mgmtRPM=false
     ;;
+    --build-docker-image)
+        buildDockerImage=true
+        ;;
     --dist-tag)
         distTag="$2"
         shift
@@ -198,9 +183,6 @@ case $key in
 	buildNum="$2"
 	shift
 	;;
-    --fast-dev-build)
-        fastDevBuild=true
-        ;;
     *)
         # unknown option
         echo "Unknown option $key"
@@ -329,12 +311,12 @@ for rpm in "${rpmsToCreate[@]}"; do
         cd RPM
     elif [ $rpm == $mgmt ]; then
         cd ..
-        requires="systemd, nodejs >= 1:17.0.0-0, nodejs < 2:19.0.0-0, mongodb-mongosh < 2.9.0, mongodb-org-tools >= 5.0, mongodb-org-tools < 9.0, nvmesh-utils >= 2.0.0"
-        requiresUbuntu="systemd, nodejs (>= 17.0.0), nodejs (<< 19.0.0), mongodb-mongosh (< 2.9.0), mongodb-org-tools (>= 5.0), mongodb-org-tools (<< 9.0), nvmesh-utils (>= 2.0.0)"
+        requires="systemd, nodejs >= 1:17.0.0-0, nodejs < 2:19.0.0-0, mongodb-mongosh >= 2.1, mongodb-mongosh < 2.6, mongodb-org-tools >= 5.0, mongodb-org-tools < 8.3, nvmesh-utils >= 2.0.0"
+        requiresUbuntu="systemd, nodejs (>= 17.0.0), nodejs (<< 19.0.0), mongodb-mongosh (>= 2.1), mongodb-mongosh (<< 2.6), mongodb-org-tools (>= 5.0), mongodb-org-tools (<< 8.3), nvmesh-utils (>= 2.0.0)"
 
         rsync -av --exclude='.git/' ../interop-db/ ./interop-db
         rsync -aRPq --exclude=*~ $management_transfer_list ~/"rpmbuild/SOURCES/$packagePrefix"
-        rm -rf ./interop-db/
+        rm -rf ./interop-db/ 
 
         #making sure all the upgrade scripts have executable permissions before packaging them
         echo "Chmoding upgrade scripts..."
@@ -343,12 +325,12 @@ for rpm in "${rpmsToCreate[@]}"; do
         find ~/"rpmbuild/SOURCES/$packagePrefix/upgradeScripts/" -maxdepth 1 ! -name '[0-9a-zA-Z]*' -type f -exec rm -f {} +
 
         #handling other vendors resources (public dir)
-        if [ "$skin" == "acme" ]; then
-            cp -Rp ~/"rpmbuild/SOURCES/$packagePrefix/public_acme"/* ~/"rpmbuild/SOURCES/$packagePrefix/public/"
+        if [ "$skin" == "micron" ]; then
+            cp -Rp ~/"rpmbuild/SOURCES/$packagePrefix/public_micron"/* ~/"rpmbuild/SOURCES/$packagePrefix/public/"
         fi
 
         #deleting other skins
-        # rm -rf ~/"rpmbuild/SOURCES/$packagePrefix/public_acme"
+        rm -rf ~/"rpmbuild/SOURCES/$packagePrefix/public_micron"
 
         mkdir ~/"rpmbuild/SOURCES/$packagePrefix/installation"
         cd RPM
@@ -372,22 +354,12 @@ for rpm in "${rpmsToCreate[@]}"; do
 
     rm -fr ~/"rpmbuild/RPMS/$ARCH/$packagePrefix"*
 
-    if [[ $fastDevBuild == true ]] && [[ $rpm == $mgmt ]]; then
-        echo "Fast dev build enabled."
-        fastDevBuildInt=1
-    else
-        fastDevBuildInt=0
-    fi
-
-    echo "Starting rpmbuild for $rpm..."
-    start_rpmbuild=$(date +%s)
-
     if [ $rpm == $utils ]; then
 	    rpmbuild -ba ~/rpmbuild/SPECS/nvmesh-$rpm.spec --define "commit_id $commitID" --define "change_id $changeID" --define "branch $branchName" --define "version $rpm_version" --define "release $rpm_release" --define "requires $requires"
         rpm_creation_retval=$?
         utilsPackageFile=$(find ~/rpmbuild/RPMS/$ARCH/$packagePrefix*)
     elif [ $rpm == $mgmt ]; then
-        rpmbuild -ba ~/rpmbuild/SPECS/nvmesh-$rpm.spec --define "commit_id $commitID" --define "change_id $changeID" --define "branch $branchName" --define "version $rpm_version" --define "release $rpm_release" --define "requires $requires" --define "fast_dev_build $fastDevBuildInt"
+        rpmbuild -ba ~/rpmbuild/SPECS/nvmesh-$rpm.spec --define "commit_id $commitID" --define "change_id $changeID" --define "branch $branchName" --define "version $rpm_version" --define "release $rpm_release" --define "requires $requires"
         rpm_creation_retval=$?
         mgmtPackageFile=$(find ~/rpmbuild/RPMS/$ARCH/$packagePrefix*)
     elif [ $rpm == $nhc ]; then
@@ -395,9 +367,6 @@ for rpm in "${rpmsToCreate[@]}"; do
         rpm_creation_retval=$?
         nhcPackageFile=$(find ~/rpmbuild/RPMS/$ARCH/$packagePrefix*)
     fi
-
-    end_rpmbuild=$(date +%s)
-    echo "rpmbuild for $rpm took $((end_rpmbuild - start_rpmbuild)) seconds."
 
     cp ~/"rpmbuild/RPMS/$ARCH/$packagePrefix"* .
 
@@ -415,3 +384,50 @@ for rpm in "${rpmsToCreate[@]}"; do
     pkgDeb
 done
 
+build_docker_image() {
+    echo "Building Docker Image from package $mgmtPackageFile with utils $utilsPackageFile"
+
+    cp $mgmtPackageFile docker/src/
+    cp $utilsPackageFile docker/src/
+
+    cd docker/src
+
+    utilsPkgFileWithoutPath=$(echo $utilsPackageFile | rev | cut -d '/' -f 1 | rev)
+    mgmtPkgFileWithoutPath=$(echo $mgmtPackageFile | rev | cut -d '/' -f 1 | rev)
+
+    ./build.sh --mgmt $mgmtPkgFileWithoutPath --utils $utilsPkgFileWithoutPath
+
+    return_code=$?
+
+    if [ "$return_code" -eq 0 ]; then
+        rm ./$mgmtPkgFileWithoutPath
+        cd ../../
+
+        export_docker_image
+        return $?
+    else
+        echo "Error building docker image"
+        return $return_code
+    fi
+}
+
+export_docker_image() {
+    full_tag="$rpm_version-$rpm_release_num"
+    tar_file_name="nvmesh-management-$full_tag.tar"
+    image_name="registry.excelero.com/nvmesh-management:$full_tag"
+
+    echo "Saving docker image $image_name to file $tar_file_name"
+
+    docker save --output "$tar_file_name" "$image_name"
+    return_code=$?
+
+    if [ "$return_code" -ne 0 ]; then
+        echo "Error saving docker image $image_name to file $tar_file_name"
+    fi
+
+    return $return_code
+}
+
+if [ "$buildDockerImage" == true ]; then
+    build_docker_image
+fi
